apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
  namespace: myfluent-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq:latest
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: myfluent-uat
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672