version: "3"
services:
  rabbitmq:
    hostname: rabbitmq
    image: masstransit/rabbitmq:latest
    container_name: sample-platform-rabbitmq
    networks:
     - network
    ports:
     - "5672:5672"
     - "15672:15672"
    healthcheck:
        timeout: 5s
        interval: 5s
        retries: 10
        test:
          - "CMD"
          - "rabbitmqctl"
          - "status"
  platform:
    image: platform-sample
    container_name: sample-platform
    networks:
     - network
    ports:
     - "5000:80"
    depends_on:
      - rabbitmq
  platform-sample-producer:
    image: platform-sample-producer
    container_name: platform-sample-producer
    environment:
      - MT_RMQ__HOST=rabbitmq
    networks:
      - network
    depends_on:
      - rabbitmq      
networks:
    network: {}
