version: "3"
services:
  rabbitmq:
    hostname: rabbitmq
    image: masstransit/rabbitmq:latest
    container_name: sample-platform-rabbitmq
    networks:
     - network
    ports:
     - "5672:5672"
     - "15672:15672"
    healthcheck:
        timeout: 5s
        interval: 5s
        retries: 10
        test:
          - "CMD"
          - "rabbitmqctl"
          - "status"
  platform:
    image: sample-platform
    container_name: sample-platform
    build:
      context: .
      dockerfile: Sample.Platform.Dockerfile
    networks:
     - network
    ports:
     - "5000:80"
    depends_on:
      - rabbitmq
  sample-platform-producer:
    image: sample-platform-producer
    container_name: sample-platform-producer
    build:
      context: .
      dockerfile: Sample.Platform.Producer.Dockerfile
    networks:
      - network
    depends_on:
      - rabbitmq
networks:
    network: {}
